### ISSUE TITLE
(bug) Why canary release return same result instead following percentage weight distribution?

### ISSUE THREAD

**Issue by sswastioyono18** [thomaspoignant/go-feature-flag#1170] opened 2023-10-22 16:57 UTC
### Observed behavior

When I tried the canary release, I expect 50-50 means sometimes it will result in true or false but turns out the result always the same just by doing simple for loop.

<img width="444" alt="image" src="https://github.com/thomaspoignant/go-feature-flag/assets/11158339/a816e2d9-9350-44e6-b2f3-51163c1e4f32">

not sure if this is expected or a bug but since it is not documented, I suppose this is a bug. 
I notice the flag will change once I put the percentage to 80:20 so the auto reload works and the flagging works but I dont think the distribution works correctly (or is this using some kind of different distribution?)

### Expected Behavior

every request should return a result based on weighted preference or some calculation from previous result (?)

### Steps to reproduce

this is my simple config flag
```
canary-flag:
  variations:
    oldBehavior: false
    canary: true
  defaultRule:
    percentage:
      oldBehavior: 50
      canary: 50
```

and this is how I load it with feature flag, the delay is to simulate config change
```
for i := 0; i < 100; i++ {
		time.Sleep(1 * time.Second)
		user := ffcontext.NewEvaluationContext("test-flag")
		hasFlag, err := ffclient.BoolVariation("canary-flag", user, false)
		if err != nil {
			fmt.Println("Error: ", err)
			return
		}
		if hasFlag {
			fmt.Println("flag 'canary-flag' is true for the user")
		} else {
			fmt.Println("flag 'canary-flag' is false for the user")
		}
	}
```

**Comment by thomaspoignant** [comment] 2023-10-22 18:30
Hello @sswastioyono18 thanks for reporting this.

Actually after looking at your code this is totally a normal behavior.
Let me try to explain you why.

GO Feature Flag has a consistent value based on the targeting key in your evaluation context.
This means that in your case the context with the targeting key `test-flag` will always have the same results when calling the function `ffclient.BoolVariation` for the associated flag `canary-flag`.
This choice has been made to be sure that the user will always see the same behavior in your application over time. Our main goal is to be sure that the behaviors of your feature behind the flag is not changing for the same user.

You canary configuration is still valid, but if you want to do some canary you should ensure that you have different targeting key for your different users. Based on that we will be able to affect 50% of your users in each variants.

I have refactor a bit your example code bellow, you can see that the targeting key will be different each time, and you will see that we will use both variants:

```go
for i := 0; i < 100; i++ {
  time.Sleep(1 * time.Second)
  user := ffcontext.NewEvaluationContext("test-flag" + i)
  hasFlag, err := ffclient.BoolVariation("canary-flag", user, false)
  if err != nil {
	fmt.Println("Error: ", err)
	return
  }
  if hasFlag {
	fmt.Println("flag 'canary-flag' is true for the user")
  } else {
	fmt.Println("flag 'canary-flag' is false for the user")
  }
}
```

To get a bit more in depth on how GO Feature Flag is affecting the variant based on the context, let me explain how it work.
We are doing a hash of the **targeting key + flag name**, and we transform it as `int32`, based on the value and the percentage we affect the right variant associated to the combination.

You can look at this [code](https://github.com/thomaspoignant/go-feature-flag/blob/02a8c6fa978377dd4d27e9a4aee9cb972256c64c/internal/flag/internal_flag.go#L129) if you want to check the implementation.

Since this is an expected behavior I will close the issue, but feel free to comment if you want more information or if you have any doubt.

**Closed by thomaspoignant** 2023-10-22 18:30 UTC
Labels: bug, needs-triage

**Comment by sswastioyono18** [comment] 2023-10-25 05:46
Hi @thomaspoignant thanks for coming back to this one.

I see, I think you are right and I probably misunderstood the basic concept of canary. 

I have the assumption that the same user can get different response when they were entering this feature flag logic. In reality, once the specific user got into the specific feature, they will have consistent result (otherwise they will probably complaint..).

Also thanks for providing a corrective example. I was interested on trying go feature flag due to the ability to load from k8s  config file which means the service don't have to call external api and handle the timeout etc. The progressive feature is also another thing that I want to try because so far in backend we don't have this kind of feature. We always do true/false release manually and hopefully this is something that can help us to reduce releasing only the changes on config file.

**Comment by thomaspoignant** [comment] 2023-10-25 07:25
@sswastioyono18 awesome, let me know if you have any other questions.
And if you have any feedback don't hesitate to share them with me, it is always a pleasure to get feedback from users of GO Feature Flag.

_You can always send me an [email](contact@gofeatureflag.org) if you don't want to do this in public_

**Comment by sswastioyono18** [comment] 2024-10-17 01:28
sorry to reply this thread (a year later), I did try this in kubernetes and surprised to see in multiple pod, the evaluation flag returned consistent flag result. It might be useful information for someone else.
