### ISSUE TITLE
Default value when there is no feature flags in the cache

### ISSUE THREAD

**Issue by aliykh** [thomaspoignant/go-feature-flag#1821] opened 2024-05-01 20:37 UTC
### Your question

On the comments, it's stated that it will return the default value when the key does not exist however I am receiving error **"flag XXX is not present or disabled"** when the configuration file is empty / blank. 

```
// BoolVariation return the value of the flag in boolean.
// An error is return if you don't have init the library before calling the function.
// If the key does not exist we return the default value.
// Note: Use this function only if you are using multiple go-feature-flag instances.
func (g *GoFeatureFlag) BoolVariation(flagKey string, ctx ffcontext.Context, defaultValue bool) (bool, error) {
	res, err := g.BoolVariationDetails(flagKey, ctx, defaultValue)
	return res.Value, err
}
```

```
usr := ffcontext.NewEvaluationContext(fmt.Sprintf("%x", time.Now().Nanosecond()))
isEnabled, err := goff.BoolVariation("first-flags", usr, false)
```

The above code is returning error not the default false value?

### Expected behaviour:
when there is no config for the specified feature, fallback to the default value. which is in the above case false

**Comment by thomaspoignant** [comment] 2024-05-02 07:10
Hello @aliykh,
Thanks for raising this question.

In your example, you have the default value `isEnabled` + an error.
The error is here to inform you that the evaluation did not happen as expected, but the value return can be used as is.

If we change a bit your example to be :
```go
usr := ffcontext.NewEvaluationContext(fmt.Sprintf("%x", time.Now().Nanosecond()))
isEnabled, err := goff.BoolVariation("first-flags", usr, true)

// in that case isEnabled will be true
```

So what I recommend here if you don't need the error is just ignoring it by doing your evaluation like this:

```go
isEnabled, _ := goff.BoolVariation("first-flags", usr, true)
```

**Comment by thomaspoignant** [comment] 2024-05-03 18:34
I will close this issue since it is an expected behaviour.
@aliykh I let you re-open it if you feel that it is needed.

**Closed by thomaspoignant** 2024-05-03 18:34 UTC
Labels: question
