### ISSUE TITLE
(bug) package hash mismatch

### ISSUE THREAD

**Issue by vellone-fabricio** [thomaspoignant/go-feature-flag#554] opened 2023-03-07 16:08 UTC
### Observed behavior

I'm using this library in a project, and the lint step at the CI pipeline is giving me this error:
![image](https://user-images.githubusercontent.com/59942224/223476984-54d8808b-6127-4b5e-9314-8c19d71e16f9.png)

Can anyone help me with this issue?
Go version: 1.20.1
Lints used:
- go-fmt
- golangci-lint: v1.51.2

I've already tried remove cache and re-download go.sum file, but it didn't fix.

### Expected Behavior

I expected to be able to lint my application without crashing my CI pipeline but using the v1.4.0 version of `go-feature-flag` I'm not able to.

It's working with v1.3.0

**Comment by thomaspoignant** [comment] 2023-03-08 17:29
Hi @vellone-fabricio, thanks for sharing this with me.
I had a look at your problem and was not able to reproduce it.

I made this repo for the test, and it worked on my side.
Can you check if you reproduce it?
https://github.com/thomaspoignant/test-go-feature-flag-1.4.0

**Comment by vellone-fabricio** [comment] 2023-03-08 23:07
Bonjour, @thomaspoignant 

Yes, sorry. I tried to reproduce again here and apparently nothing is happening....
Can you close this issue? If in the future I run into this again, I'll reopen it again. 

Thank you very much for your attention and for the rapid response!

**Comment by thomaspoignant** [comment] 2023-03-09 07:01
Thanks for letting me know.
I close the issue and feel free to re-open it if you still have the issue.

**Closed** 2023-03-09 07:02 UTC
Labels: bug, question
